version: 2

sources:
  - name: raw_sources
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: public
    tables:
      - name: rh_employes
      - name: sport_employes
      - name: activites_sportives
      - name: validation_distances
